apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxy-5gc.fullname" . }}
  labels:
    {{- include "proxy-5gc.labels" . | nindent 4 }}
data:
  URLS: |-
    [
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_AsSessionWithQoS.yaml",
        "name": "AsSessionWithQoS"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_ChargeableParty.yaml",
        "name": "ChargeableParty"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_CommonData.yaml",
        "name": "CommonData"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_CpProvisioning.yaml",
        "name": "CpProvisioning"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_DeviceTriggering.yaml",
        "name": "DeviceTriggering"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_ECRControl.yaml",
        "name": "ECRControl"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_GMDviaMBMSbyMB2.yaml",
        "name": "GMDviaMBMSbyMB2"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_GMDviaMBMSbyxMB.yaml",
        "name": "GMDviaMBMSbyxMB"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_MonitoringEvent.yaml",
        "name": "MonitoringEvent"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_MsisdnLessMoSms.yaml",
        "name": "MsisdnLessMoSms"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_NIDD.yaml",
        "name": "NIDD"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_NpConfiguration.yaml",
        "name": "NpConfiguration"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_PfdManagement.yaml",
        "name": "PfdManagement"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_ReportingNetworkStatus.yaml",
        "name": "ReportingNetworkStatus"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29122_ResourceManagementOfBdt.yaml",
        "name": "ResourceManagementOfBdt"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_AEF_Security_API.yaml",
        "name": "AEF Security API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_API_Invoker_Management_API.yaml",
        "name": "CAPIF API Invoker Management API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_Access_Control_Policy_API.yaml",
        "name": "CAPIF Access Control Policy API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_Auditing_API.yaml",
        "name": "CAPIF Auditing API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_Discover_Service_API.yaml",
        "name": "CAPIF Discover Service API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_Events_API.yaml",
        "name": "CAPIF Events API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_Logging_API_Invocation_API.yaml",
        "name": "CAPIF Logging API Invocation API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_Publish_Service_API.yaml",
        "name": "CAPIF Publish Service API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29222_CAPIF_Security_API.yaml",
        "name": "CAPIF Security API"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29502_Nsmf_PDUSession.yaml",
        "name": "Nsmf PDUSession"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29503_Nudm_EE.yaml",
        "name": "Nudm EE"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29503_Nudm_PP.yaml",
        "name": "Nudm PP"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29503_Nudm_SDM.yaml",
        "name": "Nudm SDM"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29503_Nudm_UEAU.yaml",
        "name": "Nudm UEAU"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29503_Nudm_UECM.yaml",
        "name": "Nudm UECM"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29504_Nudr_DR.yaml",
        "name": "Nudr DR"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29505_Subscription_Data.yaml",
        "name": "Subscription Data"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29507_Npcf_AMPolicyControl.yaml",
        "name": "Npcf AMPolicyControl"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29508_Nsmf_EventExposure.yaml",
        "name": "Nsmf EventExposure"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29509_Nausf_SoRProtection.yaml",
        "name": "Nausf SoRProtection"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29509_Nausf_UEAuthentication.yaml",
        "name": "Nausf UEAuthentication"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29509_Nausf_UPUProtection.yaml",
        "name": "Nausf UPUProtection"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29510_Nnrf_AccessToken.yaml",
        "name": "Nnrf AccessToken"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29510_Nnrf_NFDiscovery.yaml",
        "name": "Nnrf NFDiscovery"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29510_Nnrf_NFManagement.yaml",
        "name": "Nnrf NFManagement"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29511_N5g-eir_EquipmentIdentityCheck.yaml",
        "name": "N5g-eir EquipmentIdentityCheck"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29512_Npcf_SMPolicyControl.yaml",
        "name": "Npcf SMPolicyControl"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29514_Npcf_PolicyAuthorization.yaml",
        "name": "Npcf PolicyAuthorization"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29518_Namf_Communication.yaml",
        "name": "Namf Communication"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29518_Namf_EventExposure.yaml",
        "name": "Namf EventExposure"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29518_Namf_Location.yaml",
        "name": "Namf Location"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29518_Namf_MT.yaml",
        "name": "Namf MT"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29519_Application_Data.yaml",
        "name": "Application Data"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29519_Exposure_Data.yaml",
        "name": "Exposure Data"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29519_Policy_Data.yaml",
        "name": "Policy Data"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29520_Nnwdaf_AnalyticsInfo.yaml",
        "name": "Nnwdaf AnalyticsInfo"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29520_Nnwdaf_EventsSubscription.yaml",
        "name": "Nnwdaf EventsSubscription"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29521_Nbsf_Management.yaml",
        "name": "Nbsf Management"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29522_TrafficInfluence.yaml",
        "name": "TrafficInfluence"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29523_Npcf_EventExposure.yaml",
        "name": "Npcf EventExposure"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29525_Npcf_UEPolicyControl.yaml",
        "name": "Npcf UEPolicyControl"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29531_Nnssf_NSSAIAvailability.yaml",
        "name": "Nnssf NSSAIAvailability"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29531_Nnssf_NSSelection.yaml",
        "name": "Nnssf NSSelection"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29540_Nsmsf_SMService.yaml",
        "name": "Nsmsf SMService"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29551_Nnef_PFDmanagement.yaml",
        "name": "Nnef PFDmanagement"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29554_Npcf_BDTPolicyControl.yaml",
        "name": "Npcf BDTPolicyControl"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29571_CommonData.yaml",
        "name": "CommonData"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29572_Nlmf_Location.yaml",
        "name": "Nlmf Location"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29573_JOSEProtectedMessageForwarding.yaml",
        "name": "JOSEProtectedMessageForwarding"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29573_N32_Handshake.yaml",
        "name": "N32 Handshake"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS29594_Nchf_SpendingLimitControl.yaml",
        "name": "Nchf SpendingLimitControl"
      },
      {
        "url": "http://127.0.0.1:8080/api/v1/openapi/TS32291_Nchf_ConvergedCharging.yaml",
        "name": "Nchf ConvergedCharging"
      }
    ]
  config: |-
    {{- toJson .Values.proxy.config | nindent 4 }}