apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy-5gc.fullname" . }}
  labels:
    {{- include "proxy-5gc.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "proxy-5gc.selectorLabels" . | nindent 4 }}
