apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy-5gc.fullname" . }}
  labels:
    {{- include "proxy-5gc.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      nodePort: {{ .Values.proxy.service.nodePort }}
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
  selector:
    {{- include "proxy-5gc.selectorLabels" . | nindent 4 }}
