apiVersion: v1
kind: Service
metadata:
  name: {{ include "5gc-proxy.fullname" . }}
  labels:
    {{- include "5gc-proxy.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "5gc-proxy.selectorLabels" . | nindent 4 }}
